query {
  bestMovie {
    title
    director {
      name
      bestMovie {
        title
        director {
          name
          bestMovie {
            title
            director {
              name
              bestMovie {
                title
                director {
                  name
                  bestMovie {
                    title
                    director {
                      name
                      bestMovie {
                        title
                        director {
                          name
                          bestMovie {
                            title
                            director {
                              name
                              bestMovie {
                                title
                                director {
                                  name
                                  bestMovie {
                                    title
                                    director {
                                      name
                                      bestMovie {
                                        title
                                        director {
                                          name
                                          bestMovie {
                                            title
                                            director {
                                              name
                                              bestMovie {
                                                title
                                                director {
                                                  name
                                                  bestMovie {
                                                    title
                                                    director {
                                                      name
                                                      bestMovie {
                                                        title
                                                        director {
                                                          name
                                                          bestMovie {
                                                            title
                                                            director {
                                                              name
                                                              bestMovie {
                                                                title
                                                                director {
                                                                  name
                                                                  bestMovie {
                                                                    title
                                                                    director {
                                                                      name
                                                                      bestMovie {
                                                                        title
                                                                        director {
                                                                          name
                                                                          bestMovie {
                                                                            title
                                                                            director {
                                                                              name
                                                                              bestMovie {
                                                                                title
                                                                                director {
                                                                                  name
                                                                                  bestMovie {
                                                                                    title
                                                                                    director {
                                                                                      name
                                                                                      bestMovie {
                                                                                        title
                                                                                        director {
                                                                                          name
                                                                                          bestMovie {
                                                                                            title
                                                                                            director {
                                                                                              name
                                                                                              bestMovie {
                                                                                                title
                                                                                                director {
                                                                                                  name
                                                                                                  bestMovie {
                                                                                                    title
                                                                                                    director {
                                                                                                      name
                                                                                                      bestMovie {
                                                                                                        title
                                                                                                        director {
                                                                                                          name
                                                                                                          bestMovie {
                                                                                                            title
                                                                                                            director {
                                                                                                              name
                                                                                                              bestMovie {
                                                                                                                title
                                                                                                                director {
                                                                                                                  name
                                                                                                                  bestMovie {
                                                                                                                    title
                                                                                                                    director {
                                                                                                                      name
                                                                                                                      bestMovie {
                                                                                                                        title
                                                                                                                        director {
                                                                                                                          name
                                                                                                                          bestMovie {
                                                                                                                            title
                                                                                                                            director {
                                                                                                                              name
                                                                                                                              bestMovie {
                                                                                                                                title
                                                                                                                                director {
                                                                                                                                  name
                                                                                                                                  bestMovie {
                                                                                                                                    title
                                                                                                                                    director {
                                                                                                                                      name
                                                                                                                                      bestMovie {
                                                                                                                                        title
                                                                                                                                        director {
                                                                                                                                          name
                                                                                                                                          bestMovie {
                                                                                                                                            title
                                                                                                                                            director {
                                                                                                                                              name
                                                                                                                                              bestMovie {
                                                                                                                                                title
                                                                                                                                                director {
                                                                                                                                                  name
                                                                                                                                                  bestMovie {
                                                                                                                                                    title
                                                                                                                                                    director {
                                                                                                                                                      name
                                                                                                                                                      bestMovie {
                                                                                                                                                        title
                                                                                                                                                        director {
                                                                                                                                                          name
                                                                                                                                                          bestMovie {
                                                                                                                                                            title
                                                                                                                                                            director {
                                                                                                                                                              name
                                                                                                                                                              bestMovie {
                                                                                                                                                                title
                                                                                                                                                                director {
                                                                                                                                                                  name
                                                                                                                                                                  bestMovie {
                                                                                                                                                                    title
                                                                                                                                                                    director {
                                                                                                                                                                      name
                                                                                                                                                                      bestMovie {
                                                                                                                                                                        title
                                                                                                                                                                        director {
                                                                                                                                                                          name
                                                                                                                                                                          bestMovie {
                                                                                                                                                                            title
                                                                                                                                                                            director {
                                                                                                                                                                              name
                                                                                                                                                                              bestMovie {
                                                                                                                                                                                title
                                                                                                                                                                                director {
                                                                                                                                                                                  name
                                                                                                                                                                                }
                                                                                                                                                                              }
                                                                                                                                                                            }
                                                                                                                                                                          }
                                                                                                                                                                        }
                                                                                                                                                                      }
                                                                                                                                                                    }
                                                                                                                                                                  }
                                                                                                                                                                }
                                                                                                                                                              }
                                                                                                                                                            }
                                                                                                                                                          }
                                                                                                                                                        }
                                                                                                                                                      }
                                                                                                                                                    }
                                                                                                                                                  }
                                                                                                                                                }
                                                                                                                                              }
                                                                                                                                            }
                                                                                                                                          }
                                                                                                                                        }
                                                                                                                                      }
                                                                                                                                    }
                                                                                                                                  }
                                                                                                                                }
                                                                                                                              }
                                                                                                                            }
                                                                                                                          }
                                                                                                                        }
                                                                                                                      }
                                                                                                                    }
                                                                                                                  }
                                                                                                                }
                                                                                                              }
                                                                                                            }
                                                                                                          }
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                  }
                                                                                                }
                                                                                              }
                                                                                            }
                                                                                          }
                                                                                        }
                                                                                      }
                                                                                    }
                                                                                  }
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
